export const TMDB_CIRCUIT_TIMEOUT_MS = 10_000;
export const TMDB_CIRCUIT_ERROR_THRESHOLD_PERCENT = 50;
export const TMDB_CIRCUIT_RESET_TIMEOUT_MS = 30_000;
export const TMDB_CIRCUIT_VOLUME_THRESHOLD = 5;
